name: pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest

      - name: Build environment
        run: |
          make build
          make up

      - name: Code sniffer
        run: docker-compose -f ./docker-compose.yml exec -T --user=$(id -u) php sh -c "phpcs --standard=phpcs.xml.dist"

      - name: Unit tests
        run: docker-compose -f ./docker-compose.yml exec -T --user=$(id -u) php sh -c "php ./vendor/bin/phpunit"

      - name: Php stan
        run: docker-compose -f ./docker-compose.yml exec -T --user=$(id -u) php sh -c "php -d memory_limit=256M vendor/bin/phpstan analyse -c phpstan.neon"
